### ISSUE TITLE
Potential bug in PrefetchQuerySet

### ISSUE THREAD

**Issue by georgema1982** [ionelmc/django-prefetch#11]
On line 108, there is a piece of codes like:

```
if not isinstance(manager, PrefetchManager):
    raise InvalidPrefetch('Manager for %s is not a PrefetchManager instance.' % model)
```

I wonder if it's better if it checks if it's an instance of PrefetchManagerMixin rather than PrefetchManager. I ran into this exception when I use PrefetchManagerMixin to create a manager of my own and do a cross relationship prefetch.

**Comment by ionelmc** [comment]
Looks you're correct. The mixin was added later but the isinstance check wasn't updated. Would you make a PR to fix this?
