### ISSUE TITLE
Django 1.11

### ISSUE THREAD

**Issue by dmk23** [ionelmc/django-prefetch#15]
I've upgraded from 1.9 to 1.11 and `django_prefetch` stopped working

I traced the issue to the fact that `iterator()` no longer gets called on regular `filter` and `get` operations

For now I've addressed the issue at the application level by forcing these `iterator()` calls wherever needed

But seems like this module should be updated to retrieve the prefetch fields automatically...

Not quite sure I understand what relevant Django APIs have changed...

**Comment by fjsj** [comment]
Solved with this custom code:
```
from prefetch import PrefetchManager, PrefetchQuerySet


class CustomPrefetchQuerySet(PrefetchQuerySet):

    def _fetch_all(self):
        # Do the custom prefetchs here, not in iterator (different from PrefetchQuerySet behavior)
        super()._fetch_all()
        data = self._result_cache
        for name, (forwarders, prefetcher) in self._prefetch.items():
            prefetcher.fetch(data, name, self.model, forwarders,
                             getattr(self, '_db', None))

    def iterator(self):
        return super(PrefetchQuerySet, self).iterator()  # pylint: disable=bad-super-call


class CustomPrefetchManager(PrefetchManager):

    def get_queryset(self):
        # Fix PrefetchManager compatibility between QuerySet and Manager,
        # w/o this we can't use PrefetchManager.from_queryset
        return self._queryset_class(
            model=self.model,
            using=self._db,
            hints=self._hints,
            prefetch_definitions=self.prefetch_definitions)

```

**Comment by arski** [comment]
Is this project still maintained? Would PRs be accepted?

**Comment by arski** [comment]
@ionelmc I guess

**Comment by dmk23** [comment]
@arski doesn't look like it is... consider making a clone if you want to maintain it...

**Comment by ionelmc** [comment]
Ah sorry, I only glanced at this and thought it's a simple workaround. Yes, PRs are accepted, pls make one.
